# Generated by Django 5.2.8 on 2025-11-07 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weapon_type', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=30)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.skin')),
                ('primary_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_in', to='tracker.weapon')),
                ('secondary_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_in', to='tracker.weapon')),
            ],
        ),
    ]
