# Generated by Django 5.2.8 on 2025-11-07 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='role',
        ),
        migrations.RemoveField(
            model_name='loadout',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='weapon_type',
        ),
        migrations.AddField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loadout',
            name='primary_weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_loadouts', to='tracker.weapon'),
        ),
        migrations.AlterField(
            model_name='loadout',
            name='secondary_weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_loadouts', to='tracker.weapon'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
