# Generated by Django 5.2.8 on 2025-11-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_agent_role_remove_loadout_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadout',
            name='map',
            field=models.CharField(choices=[('Ascent', 'Ascent'), ('Bind', 'Bind'), ('Haven', 'Haven'), ('Icebox', 'Icebox'), ('Lotus', 'Lotus'), ('Sunset', 'Sunset'), ('Split', 'Split'), ('Pearl', 'Pearl')], max_length=100),
        ),
        migrations.AlterField(
            model_name='loadout',
            name='role',
            field=models.CharField(choices=[('Duelist', 'Duelist'), ('Initiator', 'Initiator'), ('Controller', 'Controller'), ('Sentinel', 'Sentinel')], max_length=100),
        ),
    ]
