# Generated by Django 5.2.8 on 2025-11-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_loadout_map_alter_loadout_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadout',
            name='role',
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('Duelist', 'Duelist'), ('Initiator', 'Initiator'), ('Controller', 'Controller'), ('Sentinel', 'Sentinel')], default='Primary', max_length=20),
            preserve_default=False,
        ),
    ]
