# Generated by Django 5.2.8 on 2025-11-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_loadout_role_agent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='rarity',
            field=models.CharField(choices=[('Select', 'Select'), ('Deluxe', 'Deluxe'), ('Premium', 'Premium'), ('Ultra', 'Ultra'), ('Exclusive', 'Exclusive')], default='Select', max_length=20),
        ),
    ]
