# Generated by Django 5.2.8 on 2025-11-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_skin_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadout',
            name='map',
            field=models.CharField(max_length=100),
        ),
    ]
