# Generated by Django 5.2.8 on 2025-11-08 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_loadout_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='loadout',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.map'),
        ),
    ]
