# Generated by Django 5.2.8 on 2025-12-09 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_map_alter_loadout_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='loadout',
            index=models.Index(fields=['user'], name='tracker_loa_user_id_de2cba_idx'),
        ),
        migrations.AddIndex(
            model_name='loadout',
            index=models.Index(fields=['map'], name='tracker_loa_map_id_092739_idx'),
        ),
    ]
