# Generated by Django 5.2.8 on 2025-12-09 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_weapon_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loadout',
            index=models.Index(fields=['agent', 'user'], name='tracker_loa_agent_i_940074_idx'),
        ),
    ]
